### ISSUE TITLE
2021 Automated DFT Lesson Updates

### ISSUE THREAD

**Issue by acrutt** [materialsproject/workshop#132]
Unclear Concepts
- the material covered in the workshop video and written documentation is very different - should make these consistent
- there's no introduction of the 4 VASP input files, specifically, what is a POSCAR?
- explaining the POTCAR warning is a bit much to follow verbally, would benefit from a written explanation
- workshop illustrates/demos concepts in VASP and asks participants to do exercises in QCHEM - the result is just practicing importing and this seems like a leap that may not benefit learning
- how do workflows connect to capabilities in pymatgen

What's Missing
- see how pymatgen can write input files (not just python objects)
- how to parse DFT code outputs
- seeing how the launchpad helps you manage multiple workflows and how the state of fireworks change
- links to github documentation to explore pymatgen.io and atomate workflows
- how can you modify and input files?
- where can I find non-vasp workflows in atomate?

Would suggest reorganizing into the following 3 lessons:
1. Writing input files
2. Parsing output files
3. Database automation

**Comment by shyamd** [comment]
Do you think you can re-org the lesson into those 3 sections first and then implement new content, do you need to implement content first?

**Comment by acrutt** [comment]
I was planning to reorganize what is there first and then begin outlining/filling in where the new content is needed. Since I'll be on vacation the last week of July, I was planning to get a head start on adding in the new content anyways and do not mind incorporating that in sooner.

**Comment by shyamd** [comment]
Yeah, definately sounds good. I broke it down to try and help spread the load out more, but you've got an idea of what you're doing so go ahead!

**Comment by ViktoriiaBaib** [comment]
Here are some general comments from me:
"Lesson.ipynb"
1. Lesson 1: The section "Input Sets": you use InputSet with parameters used for corresponding MP calculations and generate 4 input VASP files for unmodified Si structure. It would help if you could briefly mention what the user should do in the case when the defect was artificially introduced in the poscar. What will change? 
2. Maybe don't spend time on reading the structure from the POSCAR file but just mention that?
3. Lesson 2: imho it's a little confusing that we generated inputs for Si structure but analyze outputs for Al16Cr10. Why do we need to mention 2 different structures?
4. Lesson 3: I like how you compare outputs from cells 31 and 32! But later on, in cells 38-48 it gets messy as it is difficult to distinguish which job you analyze because of a heavy output. Maybe it'll be more clear if you first look at how it all goes only for the structure optimization workflow, and then only for the bandstructure workflow?
5. Overall the workshop is very well structured! You have 48 cells which will take ~40 min to run. If you want to reduce the time I'd suggest running everything up to cell 32 and then choosing only one workflow for the demonstration.

**Comment by shyamd** [comment]
> Here are some general comments from me:
> "Lesson.ipynb"
> 
> 1. Lesson 1: The section "Input Sets": you use InputSet with parameters used for corresponding MP calculations and generate 4 input VASP files for unmodified Si structure. It would help if you could briefly mention what the user should do in the case when the defect was artificially introduced in the poscar. What will change?
> 2. Maybe don't spend time on reading the structure from the POSCAR file but just mention that?
> 3. Lesson 2: imho it's a little confusing that we generated inputs for Si structure but analyze outputs for Al16Cr10. Why do we need to mention 2 different structures?
> 4. Lesson 3: I like how you compare outputs from cells 31 and 32! But later on, in cells 38-48 it gets messy as it is difficult to distinguish which job you analyze because of a heavy output. Maybe it'll be more clear if you first look at how it all goes only for the structure optimization workflow, and then only for the bandstructure workflow?
> 5. Overall the workshop is very well structured! You have 48 cells which will take ~40 min to run. If you want to reduce the time I'd suggest running everything up to cell 32 and then choosing only one workflow for the demonstration.

1. Agreed. Maybe just have a cell printing the POSCAR again and mention in the text that we can see by inspection that the defect site is now missing? Or make that a little mini-quiz?
2. Not sure I agree here. Repetition is important to build familiarity. Maybe POSCAR is not the most interesting film but a lot of tools for comp chem are about manipulating structure input files. Given that the users will have seen all the tools we have to manipulate structures. Emphasizing that this is a bolt-on that gets you to a DFT calculation is critical. 
3.  Agreed. Should stay consistent for Lessons 2 and 3. I would suggest going for the more complex structure. 
4. The big challenge is that you're trying to teach fireworks and atomate. I would drop the fireworks nuances and just keep the things necessary to run atomate. It's a hard balance since we know advanced users will need the fireworks to dive sooner, but the reality is that outside of a few groups that progression happens a lot slower due to lack of others with the necessary expertise and the workshop can't make up for that.

**Comment by acrutt** [comment]
Thank you for the feedback! 

1. I'll add printing out the POSCAR of Si with atom removed in Lesson 1 to reinforce what has changed in the structure
2. Since this is just one line, I'd like to keep it. It may not be clear that methods from an imported class can be used this way for those unfamiliar with python. But if we are running short on time during the lesson, this is something that can be cut!
3. The main reason I wanted to use the AlCr alloy output directory is the format of the outputs is simpler than Si. There is a small number of ionic steps so you can print them out easily and the calculation has just a single relaxation. The structure optimization for Si is a double relaxation which I think would make explaining what's going on more confusing. I was prioritizing consistency in lessons 1 & 3 since that would show you how to launch DFT calculations from just a structure object alone. Also the AlCr alloy is used in the exercises (they would have written input files for AlCr just before starting Lesson 2) so I think the flow will be ok.
4. Viktoriia: I reorganized a bit to go through running the simpler structure optimization workflow first and then the band structure workflow. This will also help with going with your suggestion in 5 if time becomes an issue.
4. Shyam: I don't think it is effective to teach how to use atomate without fireworks. The level of depth in the code/use of fireworks is very similar to what has been done in past years. The main changes I made was adding more descriptions so you can see how the pieces in lessons 1 & 2 connect. I think the scope of the lesson is a pretty bare bones introduction for how to run automated DFT and is appropriate for the amount of time allocated.

Revisions to the PR will be coming shortly based on this initial round of feedback!
